image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind
stages:
  - build
  - push

job1:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet restore
    - dotnet build
  tags:
    - default

job2:
  stage: push
  before_script:
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY_PASSWORD"
    - echo "$CI_REGISTRY"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "yay! logged in!"
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "yay! pushed to registry!"
  tags:
    - default
